version: "3.8"

services:
  www:
    build: .
    # restart: always
    # platform: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - ./wasm/pkg:/work/wasm/pkg
      - ./www/lib:/work/www/lib
      - ./www/dist:/work/www/dist
